name: ParaTranz To Gt Lang

on:
  issues:
    types: [ opened ]

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, '自動化:paratranz→gt-lang')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout miozune/GTNH-translation-compare
        uses: actions/checkout@v3
        with:
          repository: miozune/GTNH-translation-compare
          ref: rework
      - name: Ensure Dependencies
        uses: ./.github/actions/ensure-dependencies
      - name: Run Script
        id: check-and-parse-issue
        env:
          GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
          VALID_LABEL: 自動化:paratranz→gt-lang
          VALID_USER: ${{ github.repository_owner }}
        run: |
          poetry run python main.py parse-issue paratranz-to-gt-lang
    outputs:
      passed: ${{ steps.check-and-parse-issue.outputs.passed }}
      branch: ${{ steps.check-and-parse-issue.outputs.branch }}

  close-issue:
    name: Close Issue
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        run: gh issue close "${ISSUE_URL}" --comment "このテンプレートは内部専用であるため、自動的にクローズされました。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

  paratranz-to-gt-lang:
    name: ParaTranz To Gt Lang
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout miozune/GTNH-translation-compare
        uses: actions/checkout@v3
        with:
          repository: miozune/GTNH-translation-compare
          ref: rework
      - name: Ensure Dependencies
        uses: ./.github/actions/ensure-dependencies
      - name: Checkout Work Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check-and-parse-issue.outputs.branch }}
          path: '.repo'
      - name: Run Script
        run: >-
          poetry run python main.py action paratranz-to-gt-lang
          --repo-path='.repo'
          --issue='${{ github.event.issue.number }}'
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.0.0
        with:
          title: '[自動化] GTの言語ファイルを更新'
          labels: |
            自動化:paratranz→gt-lang
          body: |
            - #${{ github.event.issue.number }}によってトリガーされました
          base: ${{ needs.check-and-parse-issue.outputs.branch }}
          branch: automation/compare/${{ github.event.issue.number }}
          path: '.repo'
          delete-branch: true
