name: Release

on:
  push:
    tags-ignore:
      - 'latest'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Ensure temp dir
        run: mkdir -p temp
      - name: Ensure assets dir
        run: mkdir -p assets
      - name: Pack
        run: python repo/.github/scripts/pack.py
      - name: Zip
        run: |
          cd temp
          zip -r ../assets/${{ github.ref_name }}.zip ./*
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: |
            使い方はREADMEを参照してください
          files: |
            ./assets/${{ github.ref_name }}.zip
